# Generated by Django 4.0.2 on 2024-05-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commoninfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('schoolname', models.CharField(max_length=50)),
                ('indexno', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.commoninfo')),
                ('Parentsname', models.CharField(max_length=50)),
                ('percentage', models.IntegerField()),
                ('presentday', models.IntegerField()),
            ],
            bases=('myapp.commoninfo',),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.commoninfo')),
                ('Salary', models.IntegerField()),
                ('Subjectname', models.CharField(max_length=50)),
            ],
            bases=('myapp.commoninfo',),
        ),
    ]
