# Generated by Django 4.0.2 on 2024-05-10 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Parentsname',
            new_name='parentsname',
        ),
    ]
